# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: '1.0'
stages:
  - prepare
  - package
  - test
  - build
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'jultty/semtec-api'
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: jultty
  package:
    title: Packaging...
    stage: package
    image: 'maven:3.8.4-jdk-11'
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository package
  test:
    title: Testing...
    stage: test
    image: 'maven:3.8.4-jdk-11'
    commands:
      - mvn exec:java -Dexec.classpathScope=test -Dexec.mainClass=io.cucumber.core.cli.Main -Dexec.args='src/test/resources/Feature/'
  build:
    title: Building Docker Image...
    type: build
    stage: build
    image_name: jultty/semtec-api
    working_directory: ./
    tag: 'main'
    dockerfile: Dockerfile
