# client can create an option
POST http://localhost:8080/option
{
    "id": "xyz0003",
    "place": 2,
    "content": "Lorem ipsum sit dolor amet",
    "exercise_id": "ex0001T"

}

HTTP 201

POST http://localhost:8080/option
{
    "id": "xyz0004",
    "place": 3,
    "content": "Lorem ipsum sit dolor amet",
    "exercise_id": "ex0001T"

}

HTTP 201

POST http://localhost:8080/option
{
    "id": "xyz0005",
    "place": 1,
    "content": "Lorem ipsum sit dolor amet",
    "exercise_id": "ex0001T"

}

HTTP 201

POST http://localhost:8080/option
{
    "id": "xyz0006",
    "place": 2,
    "content": "Lorem ipsum sit dolor amet",
    "exercise_id": "ex0003T"

}

HTTP 201

POST http://localhost:8080/option
{
    "id": "xyz0007",
    "place": 1,
    "content": "Lorem ipsum sit dolor amet",
    "exercise_id": "ex0003T"

}

HTTP 201
