title: semtec
description: Um caderno semântico de tecnologia
author: jultty
baseurl: ""
domain: semtec.netlify.app
url: "https://semtec.netlify.app"
permalink: /:categories/:title:output_ext
twitter_username:
github_username: jultty
avatar_url: /assets/img/venn.svg
favicon: favicon.ico

# Build settings
#theme: moving
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed

kramdown:
  math_engine: mathjax
  syntax_highlighter_opts:
    disable: true

collections:
    tags:
        output: true

defaults:
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

